- hosts: all
  gather_facts: yes
  become: yes
  
  tasks:
  
  - name: set the dirname variable
    ansible.builtin.set_fact:
      dirname: "{{ ansible_date_time.iso8601_basic_short }}"
  
  - name: "create backup directory"
    file:
      path: /home/ubuntu/backups/{{ ansible_date_time.date }}/{{ dirname }}
      state: directory
      mode: '0777'
      owner: root
      group: root

  - name: backup jar file
    ansible.builtin.copy:
      src: /home/deployment/app/apiservice-1.0-SNAPSHOT.jar
      dest: /home/ubuntu/backups/{{ ansible_date_time.date }}/{{ dirname }}
      remote_src: yes
      owner: root
      group: root
      mode: '0777'

  - name: download jar file from jenkins
    ansible.builtin.get_url:
      url: '{{ URL }}'
      dest: /home/deployment/app/apiservice-2.0-SNAPSHOT.jar
      username: vikram.patil
      password: '{{ mysecret }}'
      mode: '0775'
      owner: '{{ devuser }}'
      group: '{{ devuser }}'

  - name: stop service on remote_machine
    script: /home/deployment/app/stop-apiservice.sh

  - name: Pause for 5 seconds for service to stop
    ansible.builtin.pause:
      seconds: 5
 
  - name: stop service on remote_machine
    script: /home/deployment/app/stop-apiservice.sh
 
  - name: Pause for 5 seconds for service to start
    ansible.builtin.pause:
      seconds: 5

  - name: stop service on remote_machine
    shell: sh /home/deployment/app/status-payex.sh | grep apiservice
