- hosts: web
  tasks:
  - name: "sync website"
    synchronize:
      src: site/
      dest: /usr/share/nginx/html/{{ domain }}
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no
