- hosts: all
  tasks:
  - name: "sync website"
    synchronize:
      src: site/
      dest: /usr/share/nginx/html/helloworld.info
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no
