# Execution
# ansible-playbook mount.yml

- name: Test mount and unmounts
  hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Unmount
    mount:
        path: /SFTP/File_Server_Drive/ALGORIQ/QA_USER/CARLZEISS_SFTP
        state: absent
