---
- hosts: all
  become: true
  vars:
    created_username: root

  tasks:
    - name: Create directory if it does not exist
      file:
        path: mountpoint
        state: directory
        mode: '0755'

    - name: Send variables to passwd-s3fs files
      shell:
        "echo minioadmin:minioadmin>.passwd-s3fs"
      ignore_errors: true

    - name: Change permission of password file
      file:
        path: .passwd-s3fs
        mode: '600'

    - name: mount bucket with s3fs
      shell:
        "s3fs {{ BUCKET-NAME }} {{ MOUNT-POINT }} -o passwd_file=.passwd-s3fs -o url={{ MINIO-URL }} -o use_path_request_style -o umask=0002 -o allow_other"
#         "s3fs payex /root/mountpoint -o passwd_file=.passwd-s3fs -o url=http://172.18.200.140:9000 -o use_path_request_style -o umask=0002 -o allow_other"
      ignore_errors: true
