- hosts: all
  become: true
  
- name: Add SFTPGo PPA repository
  apt_repository:
    repo: "ppa:sftpgo/sftpgo"
    update_cache: true

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install SFTPGo
  apt:
    name: "sftpgo"
    state: present
