- hosts: all
  become: yes
  
  tasks:
    - name: Add SFTPGo PPA repository
      apt_repository:
        repo: "ppa:sftpgo/sftpgo"
        update_cache: true

    - name: Install SFTPGo
      apt:
        name: "sftpgo"
        state: present
